build: false

environment:
  matrix:
  
    - PYTHON: "C:\\Python27"
      PYTHON_VERSION: "2.7.2"
      PYTHON_ARCH: "32" 

    - PYTHON: "C:\\Python36"
      PYTHON_VERSION: "3.6.3"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python36"
      PYTHON_VERSION: "3.6.3"
      PYTHON_ARCH: "64"
init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"

install:
  - "%PYTHON%/Scripts/pip.exe install codecov"
  - "%PYTHON%/python.exe setup.py install"

test_script:
  - "%PYTHON%/python.exe -m artxy test"